<div id="contenedorBloqueSolapa">
    <div class="solapaVerdeTitulos">
        <div id="spriteTerminos"><p>Políticas de privacidad y confidencialidad de la información</p></div>
    </div>
    <div class="clear"></div>
    <div class="contInfoBloques">
        <div class="texto">
            <div class="parrafoQuienes">
                <p class="tituloNaranjaFaq">T&eacute;rminos y condiciones de uso del Sitio</p>
                <p>Este contrato describe los t&eacute;rminos y condiciones generales (los "T&eacute;rminos y Condiciones Generales") aplicables al uso de los servicios ofrecidos por {<strong>Conexi&oacute;n Reciclado</strong>} ("los Servicios") dentro del sitio <a href="http://localhost/conexionagroecologica/" target="_blank">localhost/conexionagroecologica</a>&nbsp;("<strong>Conexi&oacute;n Reciclado</strong>" o el "sitio"). Cualquier persona (en adelante "Usuario" o en plural "Usuarios") que desee acceder y/o usar el sitio o los Servicios podr&aacute; hacerlo sujet&aacute;ndose a los T&eacute;rminos y Condiciones Generales respectivos, junto con todas las dem&aacute;s pol&iacute;ticas y principios que rigen&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;y que son incorporados al presente por referencia.</p>
                <p style="font-weight: bold;">CUALQUIER PERSONA QUE NO ACEPTE ESTOS T&Eacute;RMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CAR&Aacute;CTER OBLIGATORIO Y VINCULANTE, DEBER&Aacute; ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.</p>
                <p>El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los T&eacute;rminos y Condiciones Generales y en las Pol&iacute;ticas de Privacidad as&iacute; como en los dem&aacute;s documentos incorporados a los mismos por referencia, previo a su registraci&oacute;n como Usuario de&nbsp;<strong>Conexi&oacute;n Reciclado</strong>.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">01 - Capacidad</p>
                <p>Los Servicios s&oacute;lo est&aacute;n disponibles para personas f&iacute;sica o de existencia ideal que tengan capacidad legal para contratar. No podr&aacute;n utilizar los servicios las personas que no tengan esa capacidad, los menores de edad o Usuarios de&nbsp;Conexi&oacute;n Reciclado&nbsp;que hayan sido suspendidos temporalmente o inhabilitados definitivamente. Si est&aacute;s registrando un Usuario como Empresa, debes tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los t&eacute;rminos de este Acuerdo.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">02 - Registraci&oacute;n</p>
                <p>Es obligatorio completar el formulario de registraci&oacute;n en todos sus campos con datos v&aacute;lidos para poder utilizar los servicios que brinda&nbsp;<strong>Conexi&oacute;n Reciclado</strong>. El futuro Usuario deber&aacute; completarlo con su informaci&oacute;n personal de manera exacta, precisa y verdadera ("Datos Personales") y asume el compromiso de actualizar los Datos Personales conforme resulte necesario.&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;podr&aacute; utilizar diversos medios para identificar a sus Usuarios, pero&nbsp;<strong>Conexi&oacute;n Reciclado</strong> NO se responsabiliza por la certeza de los Datos Personales provistos por sus Usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados.</p>
                <p>A su exclusiva discreci&oacute;n,&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;podr&aacute; requerir una registraci&oacute;n adicional a los Usuarios.</p>
                <p><strong>Conexi&oacute;n Reciclado</strong>&nbsp;se reserva el derecho de solicitar alg&uacute;n comprobante y/o dato adicional a efectos de corroborar los Datos Personales, as&iacute; como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitaci&oacute;n, se dar&aacute; de baja todos los art&iacute;culos publicados, as&iacute; como las ofertas realizadas, sin que ello genere alg&uacute;n derecho a resarcimiento.</p>
                <p>El Usuario acceder&aacute; a su cuenta personal ("Cuenta") mediante el ingreso de su Usuario y clave de seguridad personal elegida ("Clave de Seguridad"). El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad.</p>
                <p>La Cuenta es personal, &uacute;nica e intransferible, y est&aacute; prohibido que un mismo Usuario registre o posea m&aacute;s de una Cuenta. En caso que <strong>Conexi&oacute;n Reciclado</strong> detecte distintas Cuentas que contengan datos coincidentes o relacionados, podr&aacute; cancelar, suspender o inhabilitarlas.&nbsp;</p>
                <p><br /> El Usuario ser&aacute; responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma est&aacute; restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario. El Usuario se compromete a notificar a&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;en forma inmediata y por medio id&oacute;neo y fehaciente, cualquier uso no autorizado de su Cuenta, as&iacute; como el ingreso por terceros no autorizados a la misma. Se aclara que est&aacute; prohibida la venta, cesi&oacute;n o transferencia de la Cuenta (incluyendo la reputaci&oacute;n y calificaciones) bajo ning&uacute;n t&iacute;tulo.</p>
                <p><br /> <strong>Conexi&oacute;n Reciclado</strong>&nbsp;se reserva el derecho de rechazar cualquier solicitud de registraci&oacute;n o de cancelar una registraci&oacute;n previamente aceptada, sin que est&eacute; obligado a comunicar o exponer las razones de su decisi&oacute;n y sin que ello genere alg&uacute;n derecho a indemnizaci&oacute;n o resarcimiento.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">03 - Modificaciones del Acuerdo</p>
                <p><strong>Conexi&oacute;n Reciclado</strong>&nbsp;podr&aacute; modificar los T&eacute;rminos y Condiciones Generales en cualquier momento haciendo p&uacute;blicos en el Sitio los t&eacute;rminos modificados. Todos los t&eacute;rminos modificados entrar&aacute;n en vigor a los 10 (diez) d&iacute;as de su publicaci&oacute;n.&nbsp; Se considerar&aacute; que el Usuario acepta los nuevos t&eacute;rminos y el contrato a no ser que el Usuario comunique lo contrario.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">04 - Listado de Bienes</p>
                <p><strong>4.1&nbsp;Publicaci&oacute;n de bienes y/o servicios</strong>. El Usuario deber&aacute; ofrecer a la venta, los bienes y/o servicios en las categor&iacute;as y subcategor&iacute;as apropiadas. Las publicaciones podr&aacute;n incluir textos descriptivos, gr&aacute;ficos, fotograf&iacute;as y otros contenidos y condiciones pertinentes para la venta del bien o la contrataci&oacute;n del servicio siempre que no violen ninguna disposici&oacute;n de este acuerdo, la ley nacional 24.051 o dem&aacute;s pol&iacute;ticas de&nbsp;<strong>Conexi&oacute;n Reciclado</strong>. El producto ofrecido por el Usuario Vendedor debe ser exactamente descrito en cuanto a sus condiciones y caracter&iacute;sticas relevantes. Se entiende y presume que mediante la inclusi&oacute;n del bien o servicio en<strong> Conexi&oacute;n Reciclado</strong>, el Usuario acepta que tiene la intenci&oacute;n y el derecho de vender el bien por &eacute;l ofrecido, o est&aacute; facultado para ello por su titular y lo tiene disponible para su entrega inmediata. Se establece que los precios de los productos publicados deber&aacute;n ser expresados con IVA incluido cuando corresponda la aplicaci&oacute;n del mismo, y en moneda del curso legal.&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;podr&aacute; remover cualquier publicaci&oacute;n cuyo precio no sea expresado de esta forma para evitar confusiones o malos entendidos en cuanto al precio final del producto. Se deja expresamente establecido que ninguna descripci&oacute;n podr&aacute; contener datos personales o de contacto, tales como, y sin limitarse a, n&uacute;meros telef&oacute;nicos, direcci&oacute;n de e-mail, direcci&oacute;n postal, direcciones de p&aacute;ginas de Internet que contengan datos como los mencionados anteriormente. En caso que se infrinja cualquiera de las disposiciones establecidas en esta cl&aacute;usula,&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;podr&aacute; editar el espacio, solicitar al Usuario que lo edite, o dar de baja la publicaci&oacute;n donde se encuentre la infracci&oacute;n.</p>
                <p><strong><br /> 4.2 Inclusi&oacute;n de im&aacute;genes y fotograf&iacute;as</strong></p>
                <p>El usuario puede incluir im&aacute;genes y fotograf&iacute;as del producto ofrecido siempre que las mismas se correspondan con el art&iacute;culo, salvo que se trate de bienes o productos o de servicios que por su naturaleza no permiten esa correspondencia. Conexi&oacute;n Reciclado no ser&aacute; responsable por las descripciones del producto ni por la similitud entre el producto ofrecido y las fotograf&iacute;as publicadas. El usuario declara que las im&aacute;genes son de su propiedad y que mantendr&aacute; indemne a Conexi&oacute;n Reciclado de cualquier reclamo de propiedad intelectual que pudiera surgir con relaci&oacute;n a los productos ofrecidos por el Usuario.</p>
                <p><br /> <strong>Conexi&oacute;n Reciclado</strong> podr&aacute; impedir la publicaci&oacute;n de la fotograf&iacute;a, e incluso del producto, si interpretara, a su exclusivo criterio, que la imagen no cumple con los presentes T&eacute;rminos y Condiciones.</p>
                <p><br /> <strong>4.3 Art&iacute;culos Prohibidos</strong>. S&oacute;lo podr&aacute;n ser ingresados en las listas de bienes y/o servicios ofrecidos, aquellos cuya venta no se encuentre t&aacute;cita o expresamente prohibida en los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;o por la ley vigente.</p>
                <p><br /> <strong>4.5 Protecci&oacute;n de Propiedad Intelectual</strong>.&nbsp;<strong>Conexi&oacute;n Reciclado</strong> o quienes sean titulares de derechos podr&aacute;n identificar y solicitar la remoci&oacute;n de aquellos art&iacute;culos que a su criterio infrinjan o violen sus derechos. En caso que&nbsp;<strong>Conexi&oacute;n Reciclado</strong> sospeche que se est&aacute; cometiendo o se ha cometido una actividad il&iacute;cita o infractora de derechos de propiedad intelectual o industrial,&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;se reserva el derecho de adoptar todas las medidas que entienda adecuadas, lo que puede incluir dar acceso limitado a los titulares de estos derechos a algunos de sus datos personales tal y como se describe en las Pol&iacute;ticas de Privacidad.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">05 - Privacidad de la Informaci&oacute;n</p>
                <p>Para utilizar los Servicios ofrecidos por&nbsp;<strong>Conexi&oacute;n Reciclado</strong>, los Usuarios deber&aacute;n facilitar determinados datos de car&aacute;cter personal. Su informaci&oacute;n personal se procesa y almacena en servidores o medios magn&eacute;ticos que mantienen altos est&aacute;ndares de seguridad y protecci&oacute;n tanto f&iacute;sica como tecnol&oacute;gica. Para mayor informaci&oacute;n sobre la privacidad de los Datos Personales y casos en los que ser&aacute; revelada la informaci&oacute;n personal, se pueden consultar nuestras&nbsp;<a href="politicas-de-privacidad.php">Pol&iacute;ticas de Privacidad</a>.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">06 - Obligaciones de los Usuarios</p>
                <p><strong>6.1 Obligaciones del Comprador</strong>. Durante el plazo de publicaci&oacute;n fijado por el Usuario Vendedor, los Usuarios interesados podr&aacute;n realizar una oferta de compra por el precio establecido en la publicaci&oacute;n. La oferta de venta se cierra al recibir una oferta de compra o una vez que vence el plazo de publicaci&oacute;n.</p>
                <p>El Comprador est&aacute; obligado a intentar comunicarse con el vendedor y completar la operaci&oacute;n, salvo que la operaci&oacute;n est&eacute; prohibida por la ley o los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de Conexi&oacute;n Reciclado, en cuyo caso no estar&aacute; obligado a concretar la operaci&oacute;n.</p>
                <p>Al ofertar por un art&iacute;culo el Usuario acepta quedar obligado por las condiciones de venta incluidas en la descripci&oacute;n del art&iacute;culo en la medida en que las mismas no infrinjan las leyes o los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de <strong>Conexi&oacute;n Reciclado</strong>. La oferta de compra es irrevocable salvo en circunstancias excepcionales, tales como que el vendedor cambie sustancialmente la descripci&oacute;n del art&iacute;culo despu&eacute;s de realizada alguna oferta, que exista un claro error tipogr&aacute;fico, o que no pueda verificar la identidad del vendedor.</p>
                <p>Las ofertas de compra s&oacute;lo ser&aacute;n consideradas v&aacute;lidas, una vez que hayan sido procesadas por el sistema inform&aacute;tico de <strong>Conexi&oacute;n Reciclado</strong>.</p>
                <p><strong>Impuestos</strong>. Tal como lo establece la normativa fiscal vigente, el comprador debe exigir factura o ticket al vendedor como comprobante de la  operaci&oacute;n. El vendedor no estar&aacute; obligado a emitir factura o ticket s&oacute;lo en el caso de tratarse de una persona f&iacute;sica que efect&uacute;a ventas ocasionalmente.</p>
                <p><strong>6.2. Obligaciones del Vendedor</strong>. El Usuario Vendedor debe tener capacidad legal para vender el bien objeto de su oferta.</p>
                <p>Si el Usuario Vendedor ha recibido una oferta que alcance el precio establecido en la publicaci&oacute;n, queda obligado a intentar comunicarse con el comprador y completar la operaci&oacute;n con el Usuario que haya realizado la oferta. Solamente en casos excepcionales el Vendedor podr&aacute; retractarse de la venta, tales como cuando no haya podido acordar con el Usuario Comprador sobre la forma de pago, de entrega o no sea posible verificar la verdadera identidad o dem&aacute;s informaci&oacute;n del Comprador.</p>
                <p>Dado que <strong>Conexi&oacute;n Reciclado</strong> es un punto de encuentro entre comprador y vendedor y no participa de las operaciones que se realizan entre ellos, el Vendedor ser&aacute; responsable por todas las obligaciones y cargas impositivas que correspondan por la venta de sus art&iacute;culos, sin que pudiera imput&aacute;rsele a <strong>Conexi&oacute;n Reciclado</strong> alg&uacute;n tipo de responsabilidad por incumplimientos en tal sentido.</p>
                <p><strong>Impuestos</strong>. Como se menciona anteriormente, <strong>Conexi&oacute;n Reciclado</strong> s&oacute;lo pone a disposici&oacute;n de los Usuarios un espacio virtual que les permite comunicarse mediante Internet para encontrar una forma de vender o comprar art&iacute;culos y/o servicios. <strong>Conexi&oacute;n Reciclado</strong> no tiene participaci&oacute;n alguna en el proceso de negociaci&oacute;n y perfeccionamiento del contrato definitivo entre las partes. Por eso, <strong>Conexi&oacute;n Reciclado</strong> no es responsable por el efectivo cumplimiento de las obligaciones fiscales o impositivas establecidas por la ley vigente.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">07 - Prohibiciones</p>
                <p>Los Usuarios no podr&aacute;n: (a) manipular los precios de los art&iacute;culos; (b) interferir en la puja entre distintos Usuarios; (c) mantener ning&uacute;n tipo de comunicaci&oacute;n por e-mail, o por cualquier otro medio durante la oferta del bien con ninguno de los Usuarios que participan en la misma, salvo en la secci&oacute;n de preguntas y respuestas; (d) dar a conocer sus datos personales o de otros usuarios por ning&uacute;n medio; (e) publicar o vender art&iacute;culos prohibidos por los T&eacute;rminos y Condiciones Generales, dem&aacute;s pol&iacute;ticas de&nbsp;<strong>Conexi&oacute;n Reciclado</strong> o leyes vigentes; (f) insultar o agredir a otros Usuarios; (g) utilizar su reputaci&oacute;n, calificaciones, comentarios o r&eacute;plicas recibidas en el sitio de<strong> Conexi&oacute;n Reciclado</strong> en cualquier &aacute;mbito fuera de <strong>Conexi&oacute;n Reciclado</strong>, (h) indicar de cualquier forma en sus publicaciones o preguntas y respuestas alg&uacute;n incremento o modificaci&oacute;n del precio del bien ofrecido.</p>
                <p>Este tipo de actividades ser&aacute; investigado por&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;y el infractor podr&aacute; ser sancionado con la suspensi&oacute;n o cancelaci&oacute;n de la oferta e incluso de su registraci&oacute;n como Usuario de&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;y/o de cualquier otra forma que estime pertinente, sin perjuicio de las acciones legales a que pueda dar lugar por la configuraci&oacute;n de delitos o contravenciones o los perjuicios civiles que pueda causar a los Usuarios oferentes.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">08 - Violaciones del Sistema o Bases de Datos</p>
                <p>Usted se compromete a utilizar este sitio y su contenido s&oacute;lo con fines l&iacute;citos y conforme a lo dispuesto en los acuerdos <strong>Conexi&oacute;n Reciclado</strong>.&nbsp;Est&aacute; prohibido cualquier uso del Sitio o su contenido que pueda constituir una violaci&oacute;n de cualquier ley, reglamento, regla u ordenanza o que podr&iacute;a dar lugar a responsabilidad civil o penal.&nbsp;Usted acepta, declara y garantiza que toda la informaci&oacute;n que usted env&iacute;e a trav&eacute;s de este sitio es verdadera y exacta, no es fraudulenta, ni viola ninguna ley, estatuto, ordenanza o reglamento, que no es difamatorio o calumnioso, y no contiene ninguna informaci&oacute;n o datos que tiene la intenci&oacute;n de da&ntilde;ar o interferir con cualquier sistema, datos o informaci&oacute;n.&nbsp;Cualquier uso no autorizado del Sitio, incluyendo pero no limitado a la entrada no autorizada en los sistemas de <strong>Conexi&oacute;n Reciclado,</strong> mal uso de contrase&ntilde;as o uso indebido de cualquier informaci&oacute;n publicada en el Sitio est&aacute; estrictamente prohibido.&nbsp;Usted acepta que no utilizar&aacute; ning&uacute;n robot, spider, scraper u otro medio automatizado para acceder al Sitio para cualquier prop&oacute;sito, sin nuestro permiso expreso por escrito.&nbsp;Su elegibilidad para ciertos productos o servicios est&aacute; sujeta a la determinaci&oacute;n final por <strong>Conexi&oacute;n Reciclado</strong>.</p>
                <p><br /> Usted reconoce y acepta que <strong>Conexi&oacute;n Reciclado</strong> tiene el derecho, pero no la obligaci&oacute;n, de vigilar el sitio electr&oacute;nico de vez en cuando y de revelar cualquier informaci&oacute;n personal, sin previo aviso al usuario, en relaci&oacute;n con la prevenci&oacute;n del fraude, una investigaci&oacute;n judicial, solicitud gubernamental o acci&oacute;n legal, como lo requiere la ley o reglamento, o si creemos razonablemente que es necesario o apropiado para proteger <strong>Conexi&oacute;n Reciclado</strong>, sus usuarios o del p&uacute;blico.</p>
                <p>Sin limitaci&oacute;n de otros recursos, <strong>Conexi&oacute;n Reciclado</strong> puede (i) excluir al usuario de una oferta o participar en cualquier operaci&oacute;n o transacci&oacute;n potencial facilitado por o trav&eacute;s del Sitio por cualquier motivo o sin motivo alguno, y (ii) bloquear cualquier registro si el usuario ha incumplido o amenace violar los T&eacute;rminos de Uso o se dedique a cualquier comportamiento que <strong>Conexi&oacute;n Reciclado</strong> a su exclusiva discreci&oacute;n considera que pueda tener un efecto adverso en el sitio o la reputaci&oacute;n de <strong>Conexi&oacute;n Reciclado</strong>.&nbsp;<strong>Conexi&oacute;n Reciclado</strong> se reserva&nbsp; el derecho de rechazar, suprimir de la lista, o modificar cualquier contenido o informaci&oacute;n que aparece.&nbsp;Por otra parte, <strong>Conexi&oacute;n Reciclado</strong> se el derecho a su sola discreci&oacute;n, de excluir los productos y materiales, a rechazar las ofertas u ofertas, as&iacute; como de suspender los anuncios, transacciones o servicio por completo en cualquier momento.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">09 - Sanciones. Suspensión de operaciones</p>
                <p>Sin perjuicio de otras medidas, <strong>Conexi&oacute;n Reciclado</strong> podr&aacute; advertir, suspender en forma temporal o inhabilitar definitivamente la Cuenta de un Usuario o una publicaci&oacute;n,&nbsp;aplicar una sanci&oacute;n que impacte negativamente en la reputaci&oacute;n de un Usuario, iniciar las acciones que estime pertinentes y/o suspender la prestaci&oacute;n de sus Servicios si (a) se quebrantara alguna ley, o cualquiera de las estipulaciones de los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de <strong>Conexi&oacute;n Reciclado</strong>; (b) si incumpliera sus compromisos como Usuario; (c) si se incurriera a criterio de <strong>Conexi&oacute;n Reciclado</strong> en conductas o actos dolosos o fraudulentos; (d) no pudiera verificarse la identidad del Usuario o cualquier informaci&oacute;n proporcionada por el mismo fuere err&oacute;nea; (e) <strong>Conexi&oacute;n Reciclado</strong> entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el Usuario que las public&oacute;, para <strong>Conexi&oacute;n Reciclado</strong> o para los Usuarios. En el caso de la suspensi&oacute;n o inhabilitaci&oacute;n de un Usuario, todos los art&iacute;culos que tuviera publicados y las ofertas realizadas tambi&eacute;n ser&aacute;n removidos del sistema.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">10 - Responsabilidad</p>
                <p><strong>Conexi&oacute;n Reciclado</strong>&nbsp;s&oacute;lo pone a disposici&oacute;n de los Usuarios un espacio virtual que les permite ponerse en comunicaci&oacute;n mediante Internet para encontrar una forma de vender o comprar servicios o bienes.&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;no es el propietario de los art&iacute;culos ofrecidos, no tiene posesi&oacute;n de ellos ni los ofrece en venta.&nbsp;<strong>Conexi&oacute;n Reciclado</strong> no interviene en el perfeccionamiento de las operaciones realizadas entre los Usuarios ni en las condiciones por ellos estipuladas para las mismas, por ello no ser&aacute; responsable respecto de la existencia, calidad, cantidad, estado, integridad o legitimidad de los bienes ofrecidos, adquiridos o enajenados por los Usuarios, as&iacute; como de la capacidad para contratar de los Usuarios o de la veracidad de los Datos Personales por ellos ingresados. Cada Usuario conoce y acepta ser el exclusivo responsable por los art&iacute;culos que publica para su venta y por las ofertas y/o compras que realiza.</p>
                <p>Debido a que&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;no tiene ninguna participaci&oacute;n durante todo el tiempo en que el art&iacute;culo se publica para la venta, ni en la posterior negociaci&oacute;n y perfeccionamiento del contrato definitivo entre las partes, no ser&aacute; responsable por el efectivo cumplimiento de las obligaciones asumidas por los Usuarios en el perfeccionamiento de la operaci&oacute;n. El Usuario conoce y acepta que al realizar operaciones con otros Usuarios o terceros lo hace bajo su propio riesgo. En ning&uacute;n caso&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;ser&aacute; responsable por lucro cesante, o por cualquier otro da&ntilde;o y/o perjuicio que haya podido sufrir el Usuario, debido a las operaciones realizadas o no realizadas por art&iacute;culos publicados a trav&eacute;s de&nbsp;<strong>Conexi&oacute;n Reciclado</strong>.</p>
                <p><strong>Conexi&oacute;n Reciclado</strong>&nbsp;recomienda actuar con prudencia y sentido com&uacute;n al momento de realizar operaciones con otros Usuarios. El Usuario debe tener presentes, adem&aacute;s, los riesgos de contratar con menores o con personas que se valgan de una identidad falsa.&nbsp;<strong>Conexi&oacute;n Reciclado</strong> NO ser&aacute; responsable por la realizaci&oacute;n de ofertas y/o operaciones con otros Usuarios basadas en la confianza depositada en el sistema o los Servicios brindados por&nbsp;<strong>Conexi&oacute;n Reciclado</strong>.</p>
                <p>En caso que uno o m&aacute;s Usuarios o alg&uacute;n tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a&nbsp;<strong>Conexi&oacute;n Reciclado</strong> y a sus directores, gerentes, empleados, agentes, operarios, representantes y apoderados.</p>
                <p>En virtud que el usuario vendedor tiene la facultad para eliminar preguntas o impedir a un usuario hacer preguntas u ofertas en sus publicaciones, se deja aclarado que en ese caso, el usuario ser&aacute; el exclusivo responsable por esa decisi&oacute;n y las consecuencias que pudieran acarrear.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">11 - Alcance de los servicios de Conexi&oacute;n Reciclado</p>
                <p>Este acuerdo no crea ning&uacute;n contrato de sociedad, de mandato, de franquicia, o relaci&oacute;n laboral entre&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;y el Usuario. El Usuario reconoce y acepta que&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;no es parte en ninguna operaci&oacute;n, ni tiene control alguno sobre la calidad, seguridad o legalidad de los art&iacute;culos anunciados, la veracidad o exactitud de los anuncios, la capacidad de los Usuarios para vender o comprar art&iacute;culos.&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;no puede asegurar que un Usuario completar&aacute; una operaci&oacute;n ni podr&aacute; verificar la identidad o Datos Personales ingresados por los Usuarios.&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;no garantiza la veracidad de la publicidad de terceros que aparezca en el sitio y no ser&aacute; responsable por la correspondencia o contratos que el Usuario celebre con dichos terceros o con otros Usuarios.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">12 - Fallas en el sistema</p>
                <p><strong>Conexi&oacute;n Reciclado</strong>&nbsp;no se responsabiliza por cualquier da&ntilde;o, perjuicio o p&eacute;rdida al Usuario causados por fallas en el sistema, en el servidor o en Internet.<strong> Conexi&oacute;n Reciclado</strong>&nbsp;tampoco ser&aacute; responsable por cualquier virus que pudiera infectar el equipo del Usuario como consecuencia del acceso, uso o examen de su sitio web o a ra&iacute;z de cualquier transferencia de datos, archivos, im&aacute;genes, textos, o audio contenidos en el mismo. Los Usuarios NO podr&aacute;n imputarle responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades t&eacute;cnicas o fallas en los sistemas o en Internet.&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;no garantiza el acceso y uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no estar disponible debido a dificultades t&eacute;cnicas o fallas de Internet, o por cualquier otra circunstancia ajena a&nbsp;<strong>Conexi&oacute;n Reciclado</strong>; en tales casos se procurar&aacute; restablecerlo con la mayor celeridad posible sin que por ello pueda imput&aacute;rsele alg&uacute;n tipo de responsabilidad.&nbsp;<strong>Conexi&oacute;n Reciclado</strong> no ser&aacute; responsable por ning&uacute;n error u omisi&oacute;n contenidos en su sitio web.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">13 -  Gratuidad del servicio</p>
                <p>Los servicios de <strong>ConexionReciclado</strong> son gratuitos para todos los usuarios.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">14 - Propiedad intelectual. Enlaces</p>
                <p>Los contenidos de las pantallas relativas a los servicios de&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;como as&iacute; tambi&eacute;n los programas, bases de datos, redes, archivos que permiten al Usuario acceder y usar su Cuenta, son de propiedad de&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;y est&aacute;n protegidas por las leyes y los tratados internacionales de derecho de autor, marcas, patentes, modelos y dise&ntilde;os industriales. El uso indebido y la reproducci&oacute;n total o parcial de dichos contenidos quedan prohibidos, salvo autorizaci&oacute;n expresa y por escrito de&nbsp;<strong>Conexi&oacute;n Reciclado</strong>.</p>
                <p>El Sitio puede contener enlaces a otros sitios web lo cual no indica que sean propiedad u operados por&nbsp;<strong>Conexi&oacute;n Reciclado</strong>. En virtud que&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;no tiene control sobre tales sitios, NO ser&aacute; responsable por los contenidos, materiales, acciones y/o servicios prestados por los mismos, ni por da&ntilde;os o p&eacute;rdidas ocasionadas por la utilizaci&oacute;n de los mismos, sean causadas directa o indirectamente. La presencia de enlaces a otros sitios web no implica una sociedad, relaci&oacute;n, aprobaci&oacute;n, respaldo de&nbsp;<strong>Conexi&oacute;n Reciclado</strong>&nbsp;a dichos sitios y sus contenidos.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">15 - Indemnizaci&oacute;n</p>
                <p>Usted acepta indemnizar y mantener indemne de y contra cualquiera y todas las reclamaciones, p&eacute;rdidas, gastos, demandas o responsabilidades, incluyendo honorarios de abogados y los costos incurridos por nosotros en relaci&oacute;n con cualquier demanda por parte de terceros (incluyendo cualquier reclamo de propiedad intelectual) que se deriven de su violaci&oacute;n a estos T&eacute;rminos y Condiciones Generales, el derecho internacional, federal o estatal, o derechos de cualquier otra persona, incluyendo pero no limitado a la violaci&oacute;n de los derechos de autor, marca registrada o la violaci&oacute;n de la confidencialidad de propiedad de, o derecho a la privacidad.&nbsp;Asimismo, acepta que cooperar&aacute; plenamente en la defensa de dichas reclamaciones.&nbsp;Nos reservamos el derecho de asumir la defensa exclusiva y control de cualquier asunto sujeto a indemnizaci&oacute;n por usted, y usted no podr&aacute; en ning&uacute;n caso atender cualquier reclamaci&oacute;n o cuesti&oacute;n sin el consentimiento por escrito de <strong>Conexi&oacute;n Reciclado</strong>.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">16 -Divisibilidad</p>
                <p>Si alguna disposici&oacute;n de estas T&eacute;rminos y Condiciones Generales se encuentra para ser inv&aacute;lida o inaplicable, las restantes disposiciones de estas Condiciones permanecer&aacute;n en pleno vigor y efecto.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">17 - Jurisdicci&oacute;n y Ley Aplicable</p>
                <p>Este acuerdo estar&aacute; regido en todos sus puntos por las leyes vigentes en la Rep&uacute;blica Argentina.&nbsp;<br /> <br /> Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretaci&oacute;n, alcance o cumplimiento, ser&aacute; sometida al arbitraje del Centro Empresarial de Mediaci&oacute;n y Arbitraje, de acuerdo con la reglamentaci&oacute;n vigente de dicho tribunal. La sede de dicho arbitraje ser&aacute; la Ciudad Aut&oacute;noma de Buenos Aires y los procedimientos se llevar&aacute;n a cabo en idioma castellano.</p>
                <div class="lineaPunteada"></div>
                <p>Si tienes alguna duda sobre los T&eacute;rminos y Condiciones Generales o dem&aacute;s pol&iacute;ticas y principios que rigen <strong>Conexi&oacute;n Reciclado</strong> consulta nuestra p&aacute;gina de&nbsp;<a href="preguntas-frecuentes.php">Ayuda</a>.</p>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>