<div id="contenedorBloqueSolapa">
    <div class="solapaVerdeTitulos">
        <div id="spritePoliticas"><p>Políticas de privacidad y confidencialidad de la información</p></div>
    </div>
    <div class="clear"></div>
    <div class="contInfoBloques">
        <div class="texto">
            <div class="parrafoQuienes">
                <p class="tituloNaranjaFaq">Pol&iacute;ticas de privacidad y confidencialidad de la informaci&oacute;n</p>
                <p>Estas pol&iacute;ticas de privacidad (las "Pol&iacute;ticas de Privacidad") entrar&aacute;n en vigor desde su aceptaci&oacute;n para los nuevos usuarios y est&aacute;n vigentes desde 1&ordm; de julio de 2011.</p>
                <p>La privacidad de la información de los usuarios es muy importante para Conexión Reciclado. Es por esa razón que se toman las precauciones y recaudos para resguardar su información, utilizando los mecanismos de seguridad informática de protección de la información más completos y eficaces.
                    Este documento es parte integrante de los Términos y Condiciones de Conexión Reciclado. Mediante la aceptación de los Términos y Condiciones Generales en el momento de la registración el usuario acepta las políticas aquí contenidas.
                </p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">La informaci&oacute;n que recabamos</p>
                <p>Lo primero que se debe hacer para disfrutar de los servicios de Conexi&oacute;n Reciclado es registrarse, suministrando ciertos datos personales ("Informaci&oacute;n Personal") completos y exactos. Podremos solicitar, recabar y almacenar la siguiente Informaci&oacute;n  Personal: apodo o seud&oacute;nimo para operar en el sitio de Conexi&oacute;n Reciclado, nombre, n&uacute;mero de documento o identificaci&oacute;n v&aacute;lida, informaci&oacute;n f&iacute;sica de contacto (como n&uacute;mero de tel&eacute;fono domicilio, direcci&oacute;n de e-mail, etc.). Conexi&oacute;n Reciclado podr&aacute; confirmar los datos personales suministrados acudiendo a entidades p&uacute;blicas, compa&ntilde;&iacute;as especializadas o centrales de riesgo, para lo cual nos autorizas expresamente. La informaci&oacute;n que Conexi&oacute;n Reciclado obtenga de estas entidades ser&aacute; tratada en forma confidencial.</p>
                <p>El Usuario que se registre en Conexi&oacute;n Reciclado a trav&eacute;s de su cuenta personal en una red social ("Cuenta Personal"), o de cualquier modo acceda a Conexi&oacute;n Reciclado a trav&eacute;s de su Cuenta Personal, consiente expresamente que Conexi&oacute;n Reciclado:</p>
                <ul>
                    <li> &#8226; Tenga acceso, en cualquier momento, a la totalidad de la informaci&oacute;n contenida en su Cuenta Personal, incluyendo en particular, pero sin limitaci&oacute;n, a su Informaci&oacute;n Personal, informaci&oacute;n sobre sus intereses, gustos, contactos y cualquier otro contenido alojado en su Cuenta Personal;</li>
                    <li> &#8226; Incluya en dicha cuenta, mensajes, fotograf&iacute;as, videos y cualquier otro tipo de contenido.</li>
                    <li> &#8226; Env&iacute;e al correo electr&oacute;nico del Usuario vinculado a la  Cuenta Personal, informaci&oacute;n o mensajes con la finalidad descripta en la secci&oacute;n "Uso que hacemos de la Informaci&oacute;n" abajo.</li>
                </ul>
                <p>Conexi&oacute;n Reciclado recoge y almacena autom&aacute;ticamente cierta informaci&oacute;n sobre la actividad de los usuarios y visitantes dentro de su sitio web. Tal informaci&oacute;n puede incluir la URL de la que provienen (est&eacute;n o no en nuestro sitio web), a qu&eacute; URL acceden seguidamente (est&eacute;n o no en nuestro sitio web), qu&eacute; navegador est&aacute;n usando, y sus direcciones IP. Tambi&eacute;n las p&aacute;ginas visitadas, las b&uacute;squedas realizadas, las publicaciones, compras o ventas, calificaciones y r&eacute;plicas ingresadas, mensajes en los foros, entre otra informaci&oacute;n podr&aacute; ser almacenada y retenida.</p>
                <p>Si los usuarios nos env&iacute;an correspondencia sean correos electr&oacute;nicos o cartas, o si otros usuarios o terceros nos env&iacute;an correspondencia sobre las actividades o sobre los mensajes de otros usuarios en nuestro sitio, podemos recoger y almacenar tal Informaci&oacute;n Personal, incluyendo direcciones de e-mail.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Uso que hacemos de la informaci&oacute;n</p>
                <p>Para suministrar un excelente servicio y para que los usuarios puedan realizar operaciones en forma &aacute;gil y segura, Conexi&oacute;n Reciclado requiere cierta informaci&oacute;n de car&aacute;cter personal, incluyendo direcci&oacute;n de e-mail. La recolecci&oacute;n de informaci&oacute;n nos permite ofrecer a los usuarios servicios y funcionalidades que se adecuen mejor a sus necesidades y personalizar nuestros servicios para hacer que sus experiencias con Conexi&oacute;n Reciclado sean lo m&aacute;s c&oacute;modas posible. La  Informaci&oacute;n Personal que recabamos tiene las siguientes finalidades:</p>
                <ul>
                    <li> &#8226; Ayudar al comprador y vendedor a entrar en contacto directo en la oportunidad que corresponda seg&uacute;n la modalidad de la compra. En este caso, Conexi&oacute;n Reciclado suministrar&aacute; a los interesados sus datos personales (nombre, tel&eacute;fonos, localidad y correo electr&oacute;nico), a trav&eacute;s de correo electr&oacute;nico o a trav&eacute;s del sitio. La informaci&oacute;n as&iacute; conocida por el comprador o el vendedor, s&oacute;lo podr&aacute; ser utilizada a efectos de concluir la operaci&oacute;n originada en Conexi&oacute;n Reciclado y no deber&aacute; ser empleada por ninguno de ellos con fines publicitarios o promocionales u otras actividades no relacionadas con Conexi&oacute;n Reciclado, salvo la expresa autorizaci&oacute;n del usuario.</li>
                    <li> &#8226; Desarrollar estudios internos sobre los intereses, comportamientos y demograf&iacute;a de los usuarios para comprender mejor sus necesidades e intereses y ofrecer mejores servicios o proveerles informaci&oacute;n relacionada.</li>
                    <li> &#8226; Mejorar nuestras iniciativas comerciales y promocionales y analizar las p&aacute;ginas visitadas las b&uacute;squedas realizadas por los usuarios, para mejorar nuestra oferta de contenidos y art&iacute;culos, personalizar dichos contenidos, su presentaci&oacute;n y servicios.</li>
                    <li> &#8226; Enviar informaci&oacute;n o mensajes por e-mail sobre nuevos servicios, mostrar publicidad o promociones, banners, de inter&eacute;s para nuestros usuarios, noticias sobre Conexi&oacute;n Reciclado, adem&aacute;s de la informaci&oacute;n expresamente autorizada en la secci&oacute;n de preferencias. Si el usuario lo prefiere, puede solicitar que lo excluyan de las listas para el env&iacute;o de informaci&oacute;n promocional o publicitaria. Por favor aprende a hacerlo la secci&oacute;n "Cambio de preferencias de e-mail" abajo.</li>
                    <li> &#8226; Los ganadores de las Promociones y/o concursos realizados por Conexi&oacute;n Reciclado autorizan expresamente a difundir sus nombres, datos personales e im&aacute;genes y los de sus familias, por los medios y en las formas que consideren convenientes, con fines publicitarios y/o promocionales, sin derecho a compensaci&oacute;n alguna.</li>
                    <li> &#8226; Compartir la informaci&oacute;n Personal (incluyendo direcci&oacute;n de e-mail) con los proveedores de servicios o las empresas de "outsourcing" que contribuyan a mejorar o facilitar las operaciones a trav&eacute;s de Conexi&oacute;n Reciclado, como (sin limitarse a) servicios de transporte, medios de pago, seguros o intermediarios en la gesti&oacute;n de pagos, call centers o programas de fidelidad, entre otros. Conexi&oacute;n Reciclado velar&aacute; porque se cumplan ciertos est&aacute;ndares, mediante la firma de acuerdos o convenios cuyo objeto sea la privacidad de los datos personales de nuestros usuarios. No obstante, Conexi&oacute;n Reciclado no se hace responsable por el uso indebido de la Informaci&oacute;n Personal del usuario que hagan estas compa&ntilde;&iacute;as o sitios de Internet. En algunos casos, estos proveedores de servicios ser&aacute;n quienes recojan informaci&oacute;n directamente del usuario (por ejemplo si les solicitamos que realicen encuestas o estudios). En tales casos, podr&aacute; recibir una notificaci&oacute;n acerca de la participaci&oacute;n de un proveedor de servicios en tales actividades, y quedar&aacute; a discreci&oacute;n del usuario toda la informaci&oacute;n que quiera brindarle y los usos adicionales que los proveedores decidan hacer. En caso de que facilites, por propia iniciativa informaci&oacute;n adicional a dichos prestadores de servicios directamente, tales Prestadores usar&aacute;n esta informaci&oacute;n conforme a sus propias pol&iacute;ticas de privacidad. Si decidimos revelar o compartir Informaci&oacute;n Persona con terceros que no son proveedores de servicios o empresas afiliadas o relacionadas con Conexi&oacute;n Reciclado, requeriremos tu consentimiento.&nbsp;<br /> <br /> Entre los proveedores de servicios que recogen informaci&oacute;n directamente del usuario se encuentra Google Inc., una compa&ntilde;&iacute;a de Delaware cuya oficina principal est&aacute; en 1600 Amphitheatre Parkway, Mountain View (California), CA 94043, Estados Unidos ("Google"). Mediante el uso de "cookies" (ver apartado sobre "Cookies" m&aacute;s adelante), Google obtiene cierta informaci&oacute;n sobre la actividad de los usuarios de Conexi&oacute;n Reciclado y sus direcciones IP, que es directamente transmitida y archivada por Google en los servidores de Estados Unidos. Google usar&aacute; esta informaci&oacute;n por cuenta de Conexi&oacute;n Reciclado con el prop&oacute;sito de analizar y confeccionar informes sobre la actividad de los usuarios en Internet, con miras a mejorar los servicios prestados por nuestro sitio web. Google podr&aacute; transmitir dicha informaci&oacute;n a terceros cuando as&iacute; se lo requiera la normativa aplicable, o cuando dichos terceros procesen la informaci&oacute;n por cuenta de Google. El usuario consiente expresamente el tratamiento de su informaci&oacute;n por Google en la forma y para los fines aqu&iacute; indicados.</li>
                </ul>
                <p>Suministrar la informaci&oacute;n personal de los usuarios a las entidades que intervengan en la resoluci&oacute;n de disputas entre los mismos, tales como: Compa&ntilde;&iacute;as de Seguros, Amigables Componedores o Tribunales de Arbitraje o tribunales competentes para solucionar tales disputas.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Confidencialidad de la informaci&oacute;n</p>
                <p>Una vez registrado en su sitio Web, Conexi&oacute;n Reciclado no vender&aacute;, alquilar&aacute; o compartir&aacute; la  Informaci&oacute;n Personal excepto en las formas establecidas en estas pol&iacute;ticas. Sin perjuicio de ello, el usuario consiente en forma expresa que Conexi&oacute;n Reciclado transfiera total o parcialmente la Informaci&oacute;n Personal a cualquiera de las sociedades controladas, controlantes y/o vinculadas con Conexi&oacute;n Reciclado, a cualquier t&iacute;tulo y en el momento, forma y condiciones que estime pertinentes. Haremos todo lo que est&eacute; a nuestro alcance para proteger la privacidad de la  informaci&oacute;n. Puede suceder que en virtud de &oacute;rdenes judiciales, o de regulaciones legales, nos veamos compelidos a revelar informaci&oacute;n a las autoridades o terceras partes bajo ciertas circunstancias, o bien en casos que terceras partes puedan interceptar o acceder a cierta informaci&oacute;n o transmisiones de datos en cuyo caso Conexi&oacute;n Reciclado no responder&aacute; por la informaci&oacute;n que sea revelada.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Apodo</p>
                <p>Para interactuar dentro del sitio, los usuarios deben utilizar un apodo que los identificar&aacute;. Los usuarios no tendr&aacute;n acceso a la informaci&oacute;n personal de los otros usuarios, salvo en el caso de los ofertantes de una Subasta Exclusiva y cuando hayan realizado con ellos alguna operaci&oacute;n a trav&eacute;s de nuestra plataforma, luego de la cual ambas partes recibir&aacute;n la informaci&oacute;n de la otra.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Clave Personal</p>
                <p>Para acceder a los servicios reservados &uacute;nicamente para los usuarios debidamente registrados los usuarios dispondr&aacute;n de una clave personal. Con ella podr&aacute;n comprar, vender, ofertar, calificar, entre otras actividades. Esta clave deben mantenerla bajo absoluta confidencialidad y, en ning&uacute;n caso, deber&aacute;n revelarla o compartirla con otras personas.</p>
                <p>El usuario ser&aacute; responsable de todos los actos que tengan lugar mediante el uso de su Apodo y Clave, lo que incluye hacerse cargo del pago de las tarifas que eventualmente se devenguen o por los perjuicios que puedan sufrir otros usuarios por tal motivo. Si por cualquier raz&oacute;n un usuario creyera que alguien puede conocer su clave, deber&aacute;.&nbsp;</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Menores de Edad</p>
                <p>Nuestros servicios s&oacute;lo est&aacute;n disponibles para aquellas personas que tengan capacidad legal para contratar. Por lo tanto, aquellos que no cumplan con esta condici&oacute;n deber&aacute;n abstenerse de suministrar informaci&oacute;n personal para ser incluida en nuestras bases de datos. Sin embargo, pueden hacerlo a trav&eacute;s de los padres o tutores.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">El uso de la informaci&oacute;n por otros Usuarios</p>
                <p>Para facilitar la interacci&oacute;n entre todos los miembros de la comunidad de Conexi&oacute;n Reciclado, nuestro servicio permite un acceso limitado a ciertos datos de contacto del resto de usuarios, tales como Nombre de usuario, Tel&eacute;fonos, Ciudad y direcci&oacute;n de correo electr&oacute;nico.</p>
                <p>Los usuarios s&oacute;lo podr&aacute;n utilizar la Informaci&oacute;n Personal de otros usuarios obtenida en el sitio para: (a) comunicaciones relacionadas con Conexi&oacute;n Reciclado que no constituyan comunicaciones comerciales no solicitadas, (b) utilizar servicios ofrecidos en Conexi&oacute;n Reciclado (por ejemplo: dep&oacute;sito, seguros, env&iacute;o o transporte y reclamaciones sobre fraude), y (c) cualquier otra finalidad a la que el usuario correspondiente consienta expresamente una vez le hayan sido comunicadas previamente la informaci&oacute;n legalmente requerida.</p>
                <p>Bajo ninguna circunstancia, se debe comunicar Informaci&oacute;n Personal o direcci&oacute;n de correo electr&oacute;nico de otro usuario a ning&uacute;n tercero sin nuestro consentimiento y el del usuario afectado. No se debe agregar a la agenda de direcciones de correo electr&oacute;nico (f&iacute;sica o electr&oacute;nica) los datos de ning&uacute;n usuario de Conexi&oacute;n Reciclado, ni siquiera los datos de quienes hayan adquirido alg&uacute;n art&iacute;culo ofrecido en Conexi&oacute;n Reciclado, sin que medie el consentimiento expreso de tal usuario.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Cookies</p>
                <p>El usuario y el visitante del sitio Web de Conexi&oacute;n Reciclado conoce y acepta que Conexi&oacute;n Reciclado podr&aacute; utilizar un sistema de seguimiento mediante la utilizaci&oacute;n de cookies (las "Cookies"). Las Cookies son peque&ntilde;os archivos que se instalan en el disco r&iacute;gido, con una duraci&oacute;n limitada en el tiempo que ayudan a personalizar los servicios. Tambi&eacute;n ofrecemos ciertas funcionalidades que s&oacute;lo est&aacute;n disponibles mediante el empleo de Cookies. Las Cookies se utilizan con el fin de conocer los intereses, el comportamiento y la demograf&iacute;a de quienes visitan o son usuarios de nuestro Sitio Web y de esa forma, comprender mejor sus necesidades e intereses y darles un mejor servicio o proveerle informaci&oacute;n relacionada. Tambi&eacute;n usaremos la informaci&oacute;n obtenida por intermedio de las Cookies para analizar las p&aacute;ginas navegadas por el visitante o usuario, las b&uacute;squedas realizadas, mejorar nuestras iniciativas comerciales y promocionales, mostrar publicidad o promociones, banners de inter&eacute;s, noticias sobre Conexi&oacute;n Reciclado , perfeccionar nuestra oferta de contenidos y art&iacute;culos, personalizar dichos contenidos, presentaci&oacute;n y servicios; tambi&eacute;n podremos utilizar Cookies para promover y hacer cumplir las reglas y seguridad del sitio. Conexi&oacute;n Reciclado podr&aacute; agregar Cookies en los e-mails que env&iacute;e para medir la efectividad de las promociones.</p>
                <p>Utilizamos adicionalmente las Cookies para que el usuario no tenga que introducir su clave tan frecuentemente durante una sesi&oacute;n de navegaci&oacute;n, tambi&eacute;n para contabilizar y corroborar las registraciones, la actividad del usuario y otros conceptos para el Programa MercadoSocios y otros acuerdos comerciales, siempre teniendo como objetivo de la instalaci&oacute;n de las Cookies, el beneficio del usuario que la recibe, y no ser&aacute; usado con otros fines ajenos a Conexi&oacute;n Reciclado .&nbsp;<br /> <br /> Se establece que la instalaci&oacute;n, permanencia y existencia de las Cookies en el computador del usuario depende de su exclusiva voluntad y puede ser eliminada de su computador cuando el usuario as&iacute; lo desee. Para saber como quitar las Cookies del sistema es necesario revisar la secci&oacute;n Ayuda (Help) del navegador.&nbsp;<br /> <br /> Adicionalmente, se pueden encontrar Cookies u otros sistemas similares instalados por terceros en ciertas p&aacute;ginas de nuestro sitio Web. Por ejemplo, al navegar por una p&aacute;gina creada por un usuario, puede que exista una Cookie emplazada en tal p&aacute;gina.</p>
                <p>Se aclara expresamente que estas pol&iacute;ticas cubre la utilizaci&oacute;n de Cookies por este sitio y no la utilizaci&oacute;n de Cookies por parte de anunciantes. Nosotros no controlamos el uso de Cookies por terceros.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Web Beacons</p>
                <p>Un Web beacon es una imagen electr&oacute;nica, tambi&eacute;n llamada single&#8226;pixel (1 x 1) o pixel transparente, que es colocada en c&oacute;digo de una p&aacute;gina Web. Un Web beacon tiene finalidades similares a las Cookies. Adicionalmente un Web beacon es utilizado para medir patrones de tr&aacute;fico de los usuarios de una p&aacute;gina a otra con el objeto de maximizar como fluye el tr&aacute;fico a trav&eacute;s de la Web. El usuario y el visitante del sitio Web de Conexi&oacute;n Reciclado conoce y acepta que Conexi&oacute;n Reciclado podr&aacute; utilizar un sistema de seguimiento mediante la utilizaci&oacute;n de Web beacons.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Orden de autoridades competentes &#8226; Requerimientos Legales</p>
                <p>Conexi&oacute;n Reciclado coopera con las autoridades competentes y con otros terceros para garantizar el cumplimiento de las leyes, por ejemplo en materia de protecci&oacute;n de derechos de propiedad industrial e intelectual, prevenci&oacute;n del fraude y otras materias.</p>
                <p>Conexi&oacute;n Reciclado podr&aacute; revelar la Informaci&oacute;n Personal de sus usuarios bajo requerimiento de la autoridades judiciales o gubernamentales competentes para efectos de investigaciones conducidas por ellas, aunque no exista una orden ni una citaci&oacute;n ejecutiva o judicial, o por ejemplo (y sin limitaci&oacute;n a este supuesto) cuando se trate de investigaciones de car&aacute;cter penal o de fraude o las relacionadas con pirater&iacute;a inform&aacute;tica o la violaci&oacute;n de derechos de autor. En tales situaciones, Conexi&oacute;n Reciclado colaborar&aacute; con las autoridades competentes con el fin de salvaguardar la integridad y la seguridad de la Comunidad y la de sus usuarios.</p>
                <p>Conexi&oacute;n Reciclado puede (y los usuarios lo autorizan expresamente) comunicar cualquier Informaci&oacute;n Personal sobre sus usuarios con la finalidad de cumplir la normativa aplicable y cooperar con las autoridades competentes en la medida en que discrecionalmente lo entendamos necesario y adecuado en relaci&oacute;n con cualquier investigaci&oacute;n de un il&iacute;cito o un fraude, infracci&oacute;n de derechos de propiedad industrial o intelectual, u otra actividad que sea ilegal o que pueda exponer a Conexi&oacute;n Reciclado o a sus usuarios a cualquier responsabilidad legal. Adem&aacute;s, podemos (y los usuarios lo autorizan expresamente) comunicar su nombre completo, apodo, domicilio, ciudad, regi&oacute;n, c&oacute;digo postal, pa&iacute;s, n&uacute;mero de tel&eacute;fono, direcci&oacute;n de correo electr&oacute;nico, etc. a los participantes en el Programa de Protecci&oacute;n de Propiedad Intelectual de Conexi&oacute;n Reciclado en la forma que, a nuestra discreci&oacute;n, entendamos necesaria o adecuada en relaci&oacute;n con la investigaci&oacute;n del fraude, infracci&oacute;n de derechos de propiedad industrial o intelectual, pirater&iacute;a, o cualquier otra actividad ilegal. Este derecho ser&aacute; ejercido por Conexi&oacute;n Reciclado a efectos de cooperar con el cumplimiento y ejecuci&oacute;n de la ley, independientemente que no exista una orden judicial o administrativa al efecto.</p>
                <p>Adem&aacute;s, Conexi&oacute;n Reciclado se reserva el derecho (y nos autorizas expresamente a ello) de comunicar informaci&oacute;n sobre sus usuarios a otros usuarios, entidades o terceros cuando haya motivos suficientes para considerar que la actividad de un usuario sea sospechosa de intentar o cometer un delito o intentar perjudicar a otras personas. Este derecho ser&aacute; utilizado por Conexi&oacute;n Reciclado a su entera discreci&oacute;n cuando lo considere apropiado o necesario para mantener la integridad y la seguridad de la Comunidad y la de sus usuarios, para hacer cumplir los T&eacute;rminos y Condiciones Generales y dem&aacute;s Pol&iacute;ticas del sitio y a efectos de cooperar con la ejecuci&oacute;n y cumplimiento de la ley. Este derecho ser&aacute; ejercido por Conexi&oacute;n Reciclado independientemente que no exista una orden judicial o administrativa al efecto.&nbsp;</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Seguridad. Almacenamiento de la informaci&oacute;n</p>
                <p>Conexi&oacute;n Reciclado est&aacute; obligado a cumplir con toda la normativa aplicable en materia de medidas de seguridad aplicables a la Informaci&oacute;n  Personal. Adicionalmente, Conexi&oacute;n Reciclado usa los est&aacute;ndares de la industria entre materia de protecci&oacute;n de la confidencialidad de su Informaci&oacute;n Personal, incluyendo, en otras medidas, cortafuegos ("firewalls") y Secure Socket Layers ("SSL"). Conexi&oacute;n Reciclado considera a los datos de sus usuarios como un activo que debe ser protegido de cualquier p&eacute;rdida o acceso no autorizado. Empleamos diversas t&eacute;cnicas de seguridad para proteger tales datos de accesos no autorizados por usuarios de dentro o fuera de nuestra compa&ntilde;&iacute;a. Sin embargo, es necesario tener muy en cuenta que la seguridad perfecta no existe en Internet.</p>
                <p>Por ello, Conexi&oacute;n Reciclado no se hace responsable por interceptaciones ilegales o violaci&oacute;n de sus sistemas o bases de datos por parte de personas no autorizadas. Conexi&oacute;n Reciclado, tampoco se hace responsable por la indebida utilizaci&oacute;n de la informaci&oacute;n obtenida por esos medios.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Informaci&oacute;n en la secci&oacute;n de preguntas y respuestas o foros</p>
                <p>Conexi&oacute;n Reciclado permite realizar preguntas y respuestas en las publicaciones y adem&aacute;s mantiene foros p&uacute;blicos ("Foros") que son f&aacute;ciles de usar y navegar. En estas secciones los usuarios pueden realizar comentarios, dar opiniones, plantear discusiones y temas de su inter&eacute;s en un ambiente amigable, siempre sujetos a las reglas aplicables.</p>
                <p>Te recordamos que la  Informaci&oacute;n Personal publicada en la secci&oacute;n de preguntas y respuestas o en los Foros puede ser le&iacute;da, recolectada o utilizada por cualquier persona. Conexi&oacute;n Reciclado no ser&aacute; responsable por el uso de esa Informaci&oacute;n Personal publicada por el usuario en estas secciones del sitio.</p>
                <div class="lineaPunteada"></div>
                <p class="tituloNaranjaFaq">Derechos de acceso, cancelación y rectificación de la información personal</p>
                <p>Los usuarios tienen reconocidos y podr&aacute;n ejercitar los derechos de acceder, cancelar y actualizar su Informaci&oacute;n Personal, incluyendo su direcci&oacute;n de e-mail, as&iacute; como a oponerse al tratamiento de la misma y a ser informado de las cesiones llevadas a cabo, todo ello de conformidad a lo dispuesto en la normativa aplicable. Conforme se establece en el art&iacute;culo 14, inciso 3 de la Ley N&ordm; 25.326, el titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un inter&eacute;s leg&iacute;timo al efecto.</p>
                <p>Los usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de la Informaci&oacute;n Personal facilitada, y se comprometen a mantenerla debidamente actualizada.&nbsp;</p>
                <p>Una vez registrado en Conexi&oacute;n Reciclado, el usuario podr&aacute; revisar y cambiar la informaci&oacute;n que nos ha enviado durante el proceso de registraci&oacute;n incluyendo:</p>
                <ul>
                    <li> &#8226; El Apodo y direcci&oacute;n de correo electr&oacute;nico. Sin perjuicio de los cambios que realice, Conexi&oacute;n Reciclado conservar&aacute; la  Informaci&oacute;n Personal anterior por motivos de seguridad y control del fraude.</li>
                    <li> &#8226; La informaci&oacute;n de la registraci&oacute;n como: compa&ntilde;&iacute;a, domicilio, ciudad, regi&oacute;n, c&oacute;digo postal, pa&iacute;s, n&uacute;mero principal de tel&eacute;fono, n&uacute;mero secundario de tel&eacute;fono, n&uacute;mero de fax, correo electr&oacute;nico, etc.</li>
                    <li> &#8226; La clave.</li>
                </ul>
                <p>En determinados casos, mantendremos en nuestros archivos Informaci&oacute;n Personal que nos hayas pedido que retiremos, y ello con la finalidad de resolver disputas o reclamaciones, detectar problemas o incidencias y solucionarlos, y dar cumplimiento a lo dispuesto en los T&eacute;rminos y Condiciones Generales por un per&iacute;odo de tiempo determinado por la ley. En cualquier caso, la Informaci&oacute;n Personal de un usuario no ser&aacute; inmediatamente retirada de nuestros archivos por motivos legales y t&eacute;cnicos, incluyendo sistemas de soportes de seguridad. Por tanto, no se debe esperar que toda la Informaci&oacute;n Personal sea definitivamente borrada de nuestras bases de datos.&nbsp;</p>
                <p>Los usuarios deben actualizar su Informaci&oacute;n Personal peri&oacute;dicamente conforme vaya cambiando para que los otros usuarios puedan ubicarlos cuando realicen una operaci&oacute;n.</p>
                <p>Conexi&oacute;n Reciclado podr&aacute; modificar en cualquier momento los t&eacute;rminos y condiciones de estas Pol&iacute;ticas de Privacidad y confidencialidad y/o las pr&aacute;cticas de env&iacute;o de e-mails. Si decidimos introducir alg&uacute;n cambio material a nuestras Pol&iacute;ticas de Privacidad, te notificaremos publicando una versi&oacute;n actualizada de las Pol&iacute;ticas en esta secci&oacute;n o mediante el env&iacute;o de un e-mail o inform&aacute;ndolo en la p&aacute;gina principal u otras secciones del sitio para mantenerte actualizado de los cambios realizados.</p>
                <p>Si hacemos cambios materiales en la forma que tu Informaci&oacute;n Personal es administrada te notificaremos por e-mail para que puedas tomar una decisi&oacute;n informada respecto si aceptas o no que tu Informaci&oacute;n Personal sea utilizada de esa forma. Si no aceptas esos t&eacute;rminos, en ese caso quedar&aacute; disuelto el v&iacute;nculo contractual y tu Informaci&oacute;n Personal no ser&aacute; usada de otra forma que la que fue informada al momento de recabarse.</p>
                <p>Se informa que la  Direcci&oacute;n Nacional de Protecci&oacute;n de Datos Personales, &Oacute;rgano de Control de la Ley N&ordm; 25.326, tiene la atribuci&oacute;n de atender las denuncias y reclamos que se interpongan con relaci&oacute;n al incumplimiento de las normas sobre protecci&oacute;n de datos personales.&nbsp;</p>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>